package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumeration of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Float,Int,BOOLean,
    String,Char,If,Then,Else,
    While,Function,Return,Identifier,FLOAT,
    ScientificN,INTeger,STRING,CHAR,LeftBrace,
    RightBrace,LeftParen,RightParen,Comma,Assign,
    Equal,NotEqual,Greater,GreaterEqual,Less,
    LessEqual,Plus,Minus,Or,And,
    Multiply,Divide,Comment,For,Do,
    Semicln,Not,PowerOp
}
